from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),  # gyro_mcn.h, pid_mcn.h, rc_bf.hpp
    os.path.join(cwd, "../rc/inc"),  # rc_bf.h
    os.path.join(cwd, "../param/inc"),  # param.h (getParam function)
    os.path.join(cwd, "../gyroFilter/inc"),  # gyro_mcn.h
    os.path.join(cwd, "../anotc/inc"),  # anotc_bf.h, protocolAtkpInterface.h
    os.path.join(cwd, "../motor/inc"),  # motor_bf.h (for subTaskMotorUpdate)
    os.path.join(cwd, "../imu/inc"),
    os.path.join(cwd, "../log/inc"),    
    os.path.join(cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "05_timestamp", "inc"),  # timestamp.h
]

group = DefineGroup(
    "PROJECT_BF_PID_EN",
    src,
    depend=[
        "PROJECT_BF_PID_EN",
        "PROJECT_BF_GYRO_FILTER_EN",  # Depends on gyro filter for gyro_filtered data
        "PROJECT_BF_RC_EN",  # Depends on RC module for RcBf class
        "PROJECT_BF_PARAM_EN",  # getParam function
        "PROJECT_BF_ANOTC_EN",  # Depends on ANOTC for logging functions (sendUserDatafloat6, etc.)
        # Note: PROJECT_BF_MOTOR_EN dependency is optional (handled by #ifdef in code)
    ],
    CPPPATH=include_paths,
)

Return("group")

