from building import *

cwd = GetCurrentDir()

path = []
src = []

src = Glob("./*.c")
path = [cwd]

# 定义编译组
group = DefineGroup("L2_DEVICE_03_MOTOR_01_PWM_EN", src, depend=["L2_DEVICE_03_MOTOR_01_PWM_EN"], CPPPATH=path)

Return("group")
