from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
src = []
group = []

# 获取src目录下的所有源文件
src = Glob("./src/*.c")

# 包含路径
path = [cwd, os.path.join(cwd, "inc")]
# 添加 ANOTC_TELEM 路径（如果启用 ANOTC_TELEM 输出）
if GetDepend(['TASK_TOOL_01_ANOTC_TELEM_EN']):
    anotc_telem_inc_path = os.path.join("$(PROJECT_ROOT)", "driverframework", "L0_task", "02_tools", "TASK_01_ANOTC_TELEM", "inc")
    path.append(anotc_telem_inc_path)

# 定义编译组（受 Kconfig 开关控制）
group = DefineGroup(
    "TASK_04_XL530X",
    src,
    depend=["WORK_TASK_TOF_XL530X_EN"],
    CPPPATH=path,
)

Return("group")

