from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),
    os.path.join(cwd, "../imu/inc"),
    os.path.join(cwd, "../common/inc"),  # init_sync.h 所在目录
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "06_bf_lib", "filter_imu", "inc"
    ),
    os.path.join(cwd, "../param/inc"),  # param.h (getParam function)
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "03_debugPin"
    ),  # debugPin.h 所在目录
]

group = DefineGroup(
    "PROJECT_BF_ACC_EN",
    src,
    depend=[
        "PROJECT_BF_ACC_EN",
        "PROJECT_BF_PARAM_EN",  # getParam function
        "L1_MIDDLEWARE_06_BF_LIB_FILTER_IMU_EN",
    ],
    CPPPATH=include_paths,
)

Return("group")

