from building import *

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup("RC_USING_CRSF", src, depend=["RC_USING_CRSF"], CPPPATH=path)

Return("group")
