from building import *
import os

cwd = GetCurrentDir()
src = []
include_paths = [cwd]

group = DefineGroup(
    "L1_MIDDLEWARE_05_PX4_LIB_02_MATHLIB_EN",
    src,
    depend=["L1_MIDDLEWARE_05_PX4_LIB_02_MATHLIB_EN"],
    CPPPATH=include_paths,
)

Return("group")


