from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.c")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),  # param.h, rcParam.h, pidParam.h, etc.
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "03_package", "uparam"
    ),  # uparam.h
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "06_bf_lib", "common", "inc"
    ),  # filter.h
]

group = DefineGroup(
    "PROJECT_BF_PARAM_EN",
    src,
    depend=[
        "PROJECT_BF_PARAM_EN",
    ],
    CPPPATH=include_paths,
)

Return("group")
