from building import *

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup('SPL16_001', src, depend = ['BSP_USING_SPL16_001'], CPPPATH = path)

Return('group')