from building import *
import os

cwd = GetCurrentDir()
src  = []
path = []

if GetDepend(['BSP_USING_I2C']):
    src += Glob('./*.c')
    path += [cwd]

# 定义编译组
group = DefineGroup('I2C_INTERFACE', src, depend = [''], CPPPATH = path)

env = DefaultEnvironment()

Return('group')