from building import *
import os

# 导入必要的变量
Import('env')

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []

group = []  # 初始化 group 变量为空列表

# 遍历子目录，查找并执行SConscript
list = os.listdir(cwd)
for item in list:
    item_path = os.path.join(cwd, item)
    if os.path.isdir(item_path) and os.path.isfile(os.path.join(item_path, 'SConscript')):
        # 为所有子目录自动使用variant_dir创建构建目录
        sub_group = SConscript(os.path.join(item_path, 'SConscript'), 
                              variant_dir=item, duplicate=0)
        if sub_group:
            group = group + sub_group

Return('group')