from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

path = [cwd, os.path.join(cwd, "../../../04_project/01_minifly/TASK_06_RC")]

# 获取当前目录下的所有源文件
src = Glob("./*.c")

# 定义编译组
group = DefineGroup("PROJECT_MINIFLY_TASK_STABLIZE_EN", src, depend=["PROJECT_MINIFLY_TASK_STABLIZE_EN"], CPPPATH=path)

Return('group')