from building import *
import os

cwd = GetCurrentDir()

src = Glob('./src/*.c')

inc_path = [
    os.path.join(cwd, 'inc'),
]

group = DefineGroup('init_sync', src, depend=[], CPPPATH=inc_path)

Return('group')

