from building import *

cwd = GetCurrentDir()
path = []
src = []

src = ['drvPwm.c']
path = [cwd]

if GetDepend(['L2_DEVICE_03_MOTOR_03_PWM_CMD_EN']):
    src += ['cmdMotor.c']

group = DefineGroup("L2_DEVICE_03_MOTOR_03_PWM_EN", src, depend=["L2_DEVICE_03_MOTOR_03_PWM_EN"], CPPPATH=path)

Return("group")
