from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup(
    "PROJECT_FMT_TASK01_RC_EN", src, depend=["PROJECT_FMT_TASK01_RC_EN"], CPPPATH=path
)

Return("group")
