from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [
    cwd,
    os.path.join(cwd, "inc"),
    os.path.join(cwd, "..", "..", "..", "..", "kernel", "rtthread", "components", "utilities", "ulog"),
    os.path.join(cwd, "..", "..", "..", "L1_middleWare", "05_px4_lib", "02_mathlib", "filter"),
    os.path.join(cwd, "..", "..", "..", "L1_middleWare", "05_px4_lib", "02_mathlib", "common"),
    # Matrix library: add base directory and subdirectories
    # Base directory allows <px4_platform_common/defines.h> to work
    os.path.join(cwd, "..", "..", "..", "L1_middleWare", "05_px4_lib", "03_matrix"),
    os.path.join(cwd, "..", "..", "..", "L1_middleWare", "05_px4_lib", "03_matrix", "px4_platform_common"),
]

group = DefineGroup(
    "TASK_04_WQ",
    src,
    depend=["TASK_DEMO_04_WQ_EN", "L1_MIDDLEWARE_05_PX4_LIB_02_MATHLIB_EN", "L1_MIDDLEWARE_05_PX4_LIB_03_MATRIX_EN"],
    CPPPATH=path,
)

Return("group")


