from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c") + Glob("./src/*.cpp")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup("PROJECT_PX4_TASK_RATE_CONTROL_EN", src, depend=["PROJECT_PX4_TASK_RATE_CONTROL_EN"], CPPPATH=path)

Return('group')

