from building import *
import os

cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

src = Glob("./*.c")

group = DefineGroup(
    "PROJECT_MINIFLY_TASK05_PARAM_EN", src, depend=["PROJECT_MINIFLY_TASK05_PARAM_EN"], CPPPATH=path
)

Return("group")
