from building import *
import os

cwd = GetCurrentDir()
src  = []
group = []
path = [cwd]

# 获取当前目录下的所有 .c 文件
src  = Glob('./*.c')

# 定义编译组
group = DefineGroup('anotc_telem', src, depend = [''], CPPPATH = path)

Return('group') 