from building import *

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup("DPS368", src, depend=["BSP_USING_DPS368"], CPPPATH=path)

Return("group")
