from building import *
import os

cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

src = Glob("./*.c")

group = DefineGroup(
    "TASK_TOOL_02_SD_MLOG", src, depend=["TASK_TOOL_02_SD_MLOG"], CPPPATH=path
)

Return("group")
