from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup(
    "TASK_TOOL_02_SD_MLOG", src, depend=["TASK_TOOL_02_SD_MLOG"], CPPPATH=path
)

Return("group")
