from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

# 获取当前目录下的所有源文件
src = Glob("./*.c")

# 定义编译组
group = DefineGroup(
    "WORK_TASK_GPS_TEST_EN", src, depend=["WORK_TASK_GPS_TEST_EN"], CPPPATH=path
)

Return("group")
