from building import *

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup('QMC5883L', src, depend = ['BSP_USING_MAG_QMC5883L'], CPPPATH = path)

Return('group')