from building import *

cwd = GetCurrentDir()
src = Glob("./src/*.c")
src += Glob("./src/*.cpp")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup("mpu6500", src, depend=["BSP_USING_MPU6500_MINIFLY"], CPPPATH=path)

Return("group")
