from building import *

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./*.c")
src += Glob("./*.cpp")
path = [cwd]

# 定义编译组
group = DefineGroup("mpu6500", src, depend=["BSP_USING_MPU6500_MINIFLY"], CPPPATH=path)

Return("group")
