from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup(
    "PROJECT_MINIFLY_TASK_SENSOR_EN", src, depend=["PROJECT_MINIFLY_TASK_SENSOR_EN"], CPPPATH=path
)

Return("group")
