from building import *
import os

cwd = GetCurrentDir()

src = Glob('src/*.cpp')
src += Glob('src/*.c')

inc_path = [
    os.path.join(cwd, 'inc'),
]

depend_list = ['PROJECT_BF_BMI270_EN']
# Add debugPin dependency if enabled
if GetDepend('PROJECT_BF_BMI270_DEBUG_PIN_EN'):
    depend_list.append('L1_MIDDLEWARE_01_MODULE_03_DEBUGPIN_EN')

group = DefineGroup('bmi270_bf', src, depend=depend_list, CPPPATH=inc_path)

Return('group')


