from building import *

cwd = GetCurrentDir()
src  = []
group = []
path = [cwd]
 
if GetDepend(['BSP_USING_ON_CHIP_FLASH_GG_DRV', 'SOC_SERIES_STM32F4']):
    src += ['drv_flash_f4.c']

group = DefineGroup('Drivers_gg', src, depend = [''], CPPPATH = path)

Return('group')
