from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

# 获取当前目录下的所有源文件
src = Glob("./*.c")

# 定义编译组
group = DefineGroup("TASK_2_GPS_TEST", src, depend=["BSP_USING_TASK_2_GPS_TEST"], CPPPATH=path)

Return('group')