from building import *
import os

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup("BSP_USING_BMI270", src, depend=["BSP_USING_BMI270"], CPPPATH=path)

Return("group")
