from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup('L1_MIDDLEWARE_01_MODULE_02_MATHS_EN', src, depend = ['L1_MIDDLEWARE_01_MODULE_02_MATHS_EN'], CPPPATH = path)

Return('group') 