from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,  # dyn_notch_filter.h 所在目录
    os.path.join(cwd, "inc"),
    os.path.join(cwd, "..", "..", "..", "L0_task", "04_project", "01_basic", "TASK_05_PARAM", "inc"),
]

group = DefineGroup(
    "L1_MIDDLEWARE_06_BF_LIB_FILTER_IMU_EN",
    src,
    depend=["L1_MIDDLEWARE_06_BF_LIB_FILTER_IMU_EN"],
    CPPPATH=include_paths,
)

Return("group")
