from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),
    os.path.join(cwd, "..", "..", "..", "L0_task", "04_project", "01_basic", "TASK_05_PARAM", "inc"),
]

group = DefineGroup(
    "L1_MIDDLEWARE_06_BF_LIB_FILTER_IMU",
    src,
    depend=["L1_MIDDLEWARE_06_BF_LIB_FILTER_IMU_EN", "L1_MIDDLEWARE_05_PX4_LIB_02_MATHLIB_EN", "L1_MIDDLEWARE_05_PX4_LIB_03_MATRIX_EN"],
    CPPPATH=include_paths,
)

Return("group")

