from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),  # motor_bf.h, motor_mcn.h
    os.path.join(cwd, "../common/inc"),  # init_sync.h 所在目录
    os.path.join(cwd, "../pid/inc"),  # pid_mcn.h
        os.path.join(cwd, "../rc/inc"),  # rc_aux_msg.h
    os.path.join(cwd, "../param/inc"),  # param.h (getParam function)
    os.path.join(cwd, "../anotc/inc"),  # anotc_bf.h, protocolAtkpInterface.h
    os.path.join(cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "05_timestamp", "inc"),  # timestamp.h
    os.path.join(cwd, "..", "..", "..", "..", "L1_middleWare", "03_package", "uMCN-latest", "inc"),  # uMCN.h
    os.path.join(cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "03_debugPin"),  # debugPin.h 所在目录
]

group = DefineGroup(
    "PROJECT_BF_MOTOR_EN",
    src,
    depend=[
        "PROJECT_BF_MOTOR_EN",
        "PROJECT_BF_PID_EN",  # Depends on PID module for pid_output data
        "PROJECT_BF_RC_EN",  # Depends on RC module for rc_aux (arm status) data
        "PROJECT_BF_PARAM_EN",  # getParam function for mixer configuration
        "PROJECT_BF_ANOTC_EN",  # Depends on ANOTC for logging functions (sendUserDatafloatN, etc.)
        "L1_MIDDLEWARE_01_MODULE_03_DEBUGPIN_EN",  # Required when PROJECT_BF_MOTOR_DEBUG_PIN_EN is enabled
    ],
    CPPPATH=include_paths,
)

Return("group")

