from building import *
import os

cwd = GetCurrentDir()

# 包含 C++ 源文件
src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),  # Local inc directory
]

group = DefineGroup(
    "PROJECT_BF_WORKQUEUE_MANAGE",
    src,
    depend=["PROJECT_BF_WORKQUEUE_MANAGE_EN"],
    CPPPATH=include_paths,
)

Return("group")

