from building import *
import os

cwd = GetCurrentDir()

src = Glob("./src/*.cpp")

include_paths = [
    cwd,
    os.path.join(cwd, "inc"),  # rc_bf.h
    os.path.join(cwd, "../common/inc"),  # init_sync.h 所在目录
    os.path.join(cwd, "../param/inc"),  # param.h (getParam function)
    os.path.join(
        cwd, "..", "..", "02_fmt", "01_TASK_RC", "inc"
    ),  # taskRc.h, pilot_cmd_bus_t
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "05_timestamp", "inc"
    ),  # timestamp.h
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "06_bf_lib", "common", "inc"
    ),  # filter.h, pt3Filter_t
    os.path.join(
        cwd, "..", "..", "..", "..", "L1_middleWare", "01_module", "03_debugPin"
    ),  # debugPin.h 所在目录
]

group = DefineGroup(
    "PROJECT_BF_RC_EN",
    src,
    depend=[
        "PROJECT_BF_RC_EN",
        "PROJECT_BF_PARAM_EN",  # getParam function
        "L1_MIDDLEWARE_06_BF_LIB_COMMON_EN",  # pt3Filter functions
    ],
    CPPPATH=include_paths,
)

Return("group")
