from building import *

cwd = GetCurrentDir()
path = []
src = []

src = Glob("./src/*.c")
src += Glob("./src/*.cpp")

path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup(
    "BSP_USING_SPA06_003", src, depend=["BSP_USING_SPA06_003"], CPPPATH=path
)

Return("group")
