from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

# 获取当前目录下的所有源文件
src = Glob("./*.c")

# 定义编译组，依赖同名 Kconfig 开关
group = DefineGroup(
    "PROJECT_MINIFLY_TASK_DSHOT_EN", src, depend=["PROJECT_MINIFLY_TASK_DSHOT_EN"], CPPPATH=path
)

Return("group")

