from building import *
import os

# 获取当前目录
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

# 获取当前目录下的所有源文件
src = Glob("./*.c")

# 定义编译组
group = DefineGroup(
    "TAWORK_TASK_BARO_REPORT_ENSK_04_BARO_TEST",
    src,
    depend=["WORK_TASK_BARO_REPORT_EN"],
    CPPPATH=path,
)

Return("group")
