#ifndef TASK_NRF_DEFS_H
#define TASK_NRF_DEFS_H

#include "protocolAtkpInterface.h"

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_COMMAND_EN
#include "anlCommand.h"
#endif

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_ACK_EN
#include "anlAck.h"
#endif

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_RCDATA_EN
#include "anlRcData.h"
#endif

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_POWER_EN
#include "anlPower.h"
#endif

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_REMOTE_EN
#include "anlRemote.h"
#endif

#ifdef PROJECT_MINIFLY_TASK04_DISTRIBUTE_PID_EN
#include "anlPid.h"
#endif

#define D_COMMAND_ACC_CALIB 0x01
#define D_COMMAND_GYRO_CALIB 0x02
#define D_COMMAND_MAG_CALIB 0x04
#define D_COMMAND_BARO_CALIB 0x05
#define D_COMMAND_ACC_CALIB_EXIT 0x20
#define D_COMMAND_ACC_CALIB_STEP1 0x21
#define D_COMMAND_ACC_CALIB_STEP2 0x22
#define D_COMMAND_ACC_CALIB_STEP3 0x23
#define D_COMMAND_ACC_CALIB_STEP4 0x24
#define D_COMMAND_ACC_CALIB_STEP5 0x25
#define D_COMMAND_ACC_CALIB_STEP6 0x26
#define D_COMMAND_FLIGHT_LOCK 0xA0
#define D_COMMAND_FLIGHT_ULOCK 0xA1


typedef enum {
  DOWN_COMMAND = 0x01,
  DOWN_ACK = 0x02,
  DOWN_RCDATA = 0x03,
  DOWN_POWER = 0x05,
  DOWN_FLYMODE = 0x0A,
  DOWN_PID1 = 0x10,
  DOWN_PID2 = 0x11,
  DOWN_PID3 = 0x12,
  DOWN_PID4 = 0x13,
  DOWN_PID5 = 0x14,
  DOWN_PID6 = 0x15,
  DOWN_RADIO = 0x40,

  DOWN_REMOTER = 0x50,
} downmsgID_e;

#endif /* TASK_NRF_DEFS_H */