from building import *
import os

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup(
    "WORK_TASK_BARO_REPORT_ENSK_04_BARO_TEST",
    src,
    depend=["WORK_TASK_BARO_REPORT_EN"],
    CPPPATH=path,
)

Return("group")
