from building import *
import os

cwd = GetCurrentDir()
src  = []
path = []

if GetDepend('SOC_FAMILY_AT32'):
    src += ['at32TimerConfig.c']
    path += [cwd]

group = DefineGroup('TIMER_CONFIG', src, depend = ['RT_USING_HWTIMER', 'SOC_FAMILY_AT32'], CPPPATH = path)

env = DefaultEnvironment()
env.Append(CPPPATH = [cwd])

Return('group')

