from building import *

cwd = GetCurrentDir()
src = Glob("./src/*.c")
path = [cwd, os.path.join(cwd, "inc")]

group = DefineGroup("RC_USING_SBUS", src, depend=["RC_USING_SBUS"], CPPPATH=path)

Return("group")
