from building import *
import os
Import('env')

# 获取当前目录
cwd = GetCurrentDir()
list = os.listdir(cwd)

# 初始化对象列表
objs = []

# 遍历当前目录的子目录，若存在子目录 SConscript，则使用全局 BUILD_DIR 作为变体输出目录
# for d in list:
#     path = os.path.join(cwd, d)
#     if os.path.isfile(os.path.join(path, 'SConscript')):
#         vdir = os.path.join(env['BUILD_DIR'], d)
#         objs = objs + SConscript(os.path.join(d, 'SConscript'), variant_dir=vdir, duplicate=0)

Return('objs')
