from building import *
import os
 
cwd     = GetCurrentDir()
CPPPATH = [cwd]
src  = []
group = []
 
list = os.listdir(cwd)
for item in list:
    item_path = os.path.join(cwd, item)
    if os.path.isdir(item_path) and os.path.isfile(os.path.join(item_path, 'SConscript')):
        sub_group = SConscript(os.path.join(cwd, item, 'SConscript'), 
                              variant_dir=item, duplicate=0)
        group = group + sub_group
 
Return('group')