from building import *
import os

# Get current directory
cwd = GetCurrentDir()
path = [cwd]
src = []
group = []

src = Glob("./*.c")

group = DefineGroup(
    "TASK_DEMO_02_UART_TEST_EN", src, depend=["TASK_DEMO_02_UART_TEST_EN"], CPPPATH=path
)

Return("group") 